# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Qgis-mapCompimentizer
                                 A QGIS plugin
 Exports a QGIS project into a MapComponents webGis
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-11-03
        copyright            : (C) 2023 by MapComponents
        email                : martin.alzueta@wheregroup.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Qgis-mapCompimentizer class from file Qgis-mapCompimentizer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .qgis_map_compimentizer import Qgis-mapCompimentizer
    return Qgis-mapCompimentizer(iface)
